spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO}
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  security:
    user:
      name: admin
      password: $2a$10$PWsMRaqvvn89S12bPVN/a.tXIQ1j8xiQP87oDl1nOrGUNzQMgoKjO
server:
  port: ${SERVER_PORT}
jwt:
  secret: ${JWT_SECRET}

cloud:
  aws:
    s3:
      bucket: ${BUCKET_NAME}
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: ${BUCKET_REGION}
    stack:
      auto: false
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: ${PROMETHEUS_BASE_PATH}
  metrics:
    tags:
      application: sw-contest